[package]
name = "clrs-compiler"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clrs-pe = { path = "../clrs-pe" }
goblin = "0.4.3"
scroll = "0.10.2"
wasm-encoder = "0.6.0"
